name = "Default"
author = "Bees"

[[npcs]]
id = 1
keywords = ["rhane", "knight", "tired", "faerie"]
formal-name = "Rhane, knight of the Willow Kingdom"
room-description = "A tired faerie slumps against the hilt of her greatsword."
description = '''
She doesn't bother to make eye contact as she asks you,
"Why did you come to this forsaken place?"
Do you have an answer for her?
'''
pronoun = "She"
in-room = 2 # TODO: I think we'll want a reset mechanism instead of going by this field (which is for player chars)

[[objects]]
id = 1
keywords = ["greatsword", "sword", "battered"]
name = "an old greatsword"
room-description = "This battered sword has seen better days."
description = '''
Most of the blade has lost its edge, and faint traces of rust
creep out of the hilt.
'''
object-type = "Weapon"

[[rooms]]
id = 1
name = "The first room"
description = '''
The room is draped in a soft, dark fabric, but
you can see the glow of moonlight seeping through
the folds.
'''
exits = [
    { dir = "North", to = 2 }
]

[[rooms]]
id = 2
name = "The second room"
description = '''
The room is hard, flat marble. Bare on all sides.
You can't tell where the light is coming from.
Maddening.
'''
exits = [
    { dir = "South", to = 1 },
    { dir = "North", to = 3 },
]

[[rooms]]
id = 3
name = "The third room"
description = '''
You're in a cozy study with a crackling fireplace.
A wall of bookcases promises to distract you from
the dreadful weather outside.
'''
exits = [
    { dir = "South", to = 2 }
]
load-objects = [
    1 # TODO: we're not doing this; this is just for testing
]
